#!/usr/bin/env bash
cd $HOME/Tshake
token="1070736066:AAE-8VNb3Tqg-JxskoJerFbR6KKbrKiMb0c"
rm -fr Tshake.lua
wget "https://raw.githubusercontent.com/tXxXr/Tshake/master/Tshake.lua"
while(true) do
rm -fr ../.telegram-cli
./tg -s ./Tshake.lua -p PROFILE --bot=$token
done
